from pydantic import BaseModel
from openai import AzureOpenAI
from azure.identity import (
    ManagedIdentityCredential,
    AzureCliCredential,
    ChainedTokenCredential,
)
from PIL import Image
from azure.ai.vision.imageanalysis import ImageAnalysisClient
from azure.ai.vision.imageanalysis.models import VisualFeatures
from core.util.service_bus_util import ServiceBusUtil
from core.util.enum import PINSService
import os
import traceback
from io import BytesIO
from uuid import uuid4


"""
Contains various utility functions to test connectivity to azure services
"""


def send_llm_message():
    """
    Send a simple message to the llm and extract the response
    """
    azure_endpoint = os.environ.get("OPENAI_ENDPOINT", None)
    credential = ChainedTokenCredential(
        ManagedIdentityCredential(), AzureCliCredential()
    )
    token = credential.get_token("https://cognitiveservices.azure.com/.default").token
    llm = AzureOpenAI(
        azure_endpoint=azure_endpoint,
        api_version="2024-12-01-preview",
        azure_ad_token=token,
    )

    class SampleResultFormat(BaseModel):
        some_strings: list[str]

    try:
        response = llm.chat.completions.parse(
            model="gpt-4.1",
            messages=[
                {"role": "system", "content": "Respond with a json list"},
                {"role": "user", "content": "Hello there"},
            ],
            temperature=0.5,
            max_tokens=1000,
            response_format=SampleResultFormat,
        )
        resp: SampleResultFormat = response.choices[0].message.parsed
        return f"Message successfully generated by the llm: '{resp.some_strings}'"
    except Exception as e:
        return "".join(traceback.TracebackException.from_exception(e).format())


def analyse_image():
    """
    Send a simple message to Azure Computer Vision and extract the response
    """
    image = Image.new("RGB", (512, 512))
    byte_stream = BytesIO()
    image.save(byte_stream, format="PNG")
    image_bytes = byte_stream.getvalue()
    try:
        azure_endpoint = os.environ.get("AZURE_VISION_ENDPOINT", None)
        credential = ChainedTokenCredential(
            ManagedIdentityCredential(), AzureCliCredential()
        )
        vision_client = ImageAnalysisClient(
            endpoint=azure_endpoint, credential=credential
        )
        result = vision_client.analyze(
            image_bytes,
            [VisualFeatures.PEOPLE],
        )
        return f"Connection with Azure Computer Vision was successful and returned the result {result}"
    except Exception as e:
        return "".join(traceback.TracebackException.from_exception(e).format())


def send_service_bus_message():
    message = str(uuid4())
    message = {"test_connectivity": message}
    try:
        ServiceBusUtil().send_redaction_process_complete_message(
            PINSService.REDACTION_SYSTEM, message
        )
    except Exception as e:
        return "".join(traceback.TracebackException.from_exception(e).format())
    return f"Successfully sent a message to subscription {PINSService.REDACTION_SYSTEM} with content {message}"
