import os
import requests


def test_llm_connection_from_azure_function():
    """
    Test that the function app is able to communicate with the llm
    """
    function_base_url = os.environ.get("FUNCTION_BASE_URL")
    function_key = os.environ.get("FUNCTION_KEY")
    url = f"{function_base_url}/testllm?code={function_key}"
    resp = requests.get(url)
    assert "Message successfully generated by the llm" in resp
