import os
import requests


def test_llm_connection_from_azure_function():
    """
    Test that the function app is able to communicate with the llm
    """
    function_base_url = os.environ.get("FUNCTION_BASE_URL")
    function_app_key = os.environ.get("FUNCTION_APP_KEY")
    url = f"{function_base_url}/api/testllm"
    resp: requests.Response = requests.get(url, params={"code": function_app_key})
    assert "Message successfully generated by the llm" in resp.text
