import os
import requests
from dotenv import load_dotenv


load_dotenv()


def trigger_azure_function(endpoint: str) -> requests.Response:
    function_base_url = os.environ.get("FUNCTION_BASE_URL")
    function_app_key = os.environ.get("FUNCTION_APP_KEY")
    url = f"{function_base_url}/api/{endpoint}?code={function_app_key}"
    return requests.get(url)


def test_llm_connection_from_azure_function():
    """
    Test that the function app is able to communicate with the llm
    """
    resp = trigger_azure_function("testllm")
    assert resp.status_code == 200
    assert "Message successfully generated by the llm" in resp.text


def test_azure_vision_connection_from_azure_function():
    """
    Test that the function app is able to communicate with Azure Computer Vision
    """
    resp = trigger_azure_function("testazurecomputervision")
    assert resp.status_code == 200
    assert "metadata" in resp
