import os
import requests
from dotenv import load_dotenv


load_dotenv()


def _trigger_azure_function(
    function_base_url: str, function_app_key: str, endpoint: str
) -> requests.Response:
    url = f"{function_base_url}/api/{endpoint}?code={function_app_key}"
    return requests.get(url)


def trigger_receiver_azure_function(endpoint: str) -> requests.Response:
    function_base_url = os.environ.get("FUNCTION_RECEIVER_BASE_URL")
    function_app_key = os.environ.get("FUNCTION_RECEIVER_APP_KEY")
    return _trigger_azure_function(function_base_url, function_app_key, endpoint)


def trigger_processor_azure_function(endpoint: str) -> requests.Response:
    function_base_url = os.environ.get("FUNCTION_PROCESSOR_BASE_URL")
    function_app_key = os.environ.get("FUNCTION_PROCESSOR_APP_KEY")
    return _trigger_azure_function(function_base_url, function_app_key, endpoint)


def test_llm_connection_from_azure_function():
    """
    Test that the function app is able to communicate with the llm
    """
    resp = trigger_processor_azure_function("testllm")
    assert resp.status_code == 200
    fail_message = f"Expected 'Message successfully generated by the llm' to be in the response, but was '{resp.text}'"
    assert "Message successfully generated by the llm" in resp.text, fail_message


def test_azure_vision_connection_from_azure_function():
    """
    Test that the function app is able to communicate with Azure Computer Vision
    """
    resp = trigger_processor_azure_function("testazurecomputervision")
    assert resp.status_code == 200
    assert "metadata" in resp.text, (
        f"Expected a 'metadata' property to be in the response, but the response was '{resp.text}'"
    )
