name: Redaction CI/CD

# This is the main CI/CD pipeline of the the redaction system
parameters:
# User-specified environment to deploy to
- name: env
  default: 'dev'
  values:
  - 'dev'
  - 'test'
  - 'prod'

# Run when Pull Request raised to the main branch
pr:
- main

# Run when merged into main
trigger:
 branches:
  include:
    - main

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    validateName: Redaction CI
    globalVariables:
      - template: pipelines/azure-pipelines-variables.yml@self
    validationJobs:
      - name: ValidateCode
        steps:
          - checkout: self
            clean: true
          - script: |
              set -e
              cd redaction-system
              python3 -m pip install ruff
              export PYTHONPATH=$(pwd)
              python3 -m ruff check redactor
              python3 -m ruff format --check redactor
            displayName: 'Python code style check'
      - name: RunTestsJob
        steps:
          - checkout: self
            clean: true
          - checkout: templates
          - template: ../steps/azure_auth.yml@templates
            parameters:
              subscriptionId: $(SUBSCRIPTION_ID_${{ upper(parameters.env) }})
          - script: |
              set -e
              cd redaction-system
              python3 -m pip install -r redactor/requirements.txt
            displayName: 'Install requirements'
          - script: |
              set -e
              cd redaction-system/redactor
              export PYTHONPATH=$(pwd)
              python3 -m pytest test/unit_test -vv -rP -n 4 --junitxml=junit/unit_test_results.xml --cov="core" --cov-report=xml:unit_test_coverage.xml
              python3 -m coverage report --fail-under=$(unitTestCoverageThreshold) --show-missing
              mv .coverage .coverage.unit
            displayName: 'Run unit tests'
          - task: PublishTestResults@2
            displayName: 'Publish unit test results'
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/unit_test_results.xml'
              testRunTitle: 'Redaction System unit test report - $(Build.BuildId) - $(Build.SourceBranch)'
              mergeTestResults: true
          # - script: |
          #     set -e
          #     cd redaction-system/redactor
          #     export PYTHONPATH=$(pwd)
          #     python3 -m pytest test/integration_test -vv -rP -n 4 --junitxml=junit/integration_test_results.xml --cov="core" --cov-report=xml:integration_test_coverage.xml
          #     python3 -m coverage report --fail-under=$(integrationTestCoverageThreshold) --show-missing
          #     mv .coverage .coverage.integration
          #   displayName: 'Run integration tests'
          # - task: PublishTestResults@2
          #   displayName: 'Publish integration test results'
          #   condition: succeededOrFailed()
          #   inputs:
          #     testResultsFiles: '**/integration_test_results.xml'
          #     testRunTitle: 'Redaction System integration test report - $(Build.BuildId) - $(Build.SourceBranch)'
          #     mergeTestResults: true


          # ----------------------------
          # E2E: start local host + run tests + always clean up + publish logs
          # ----------------------------

          - task: NodeTool@0
            displayName: 'Install Node.js (for Functions Core Tools + Azurite)'
            inputs:
              versionSpec: '20.x'

          - script: |
              set -e
              node --version
              npm --version
            displayName: 'Verify Node/npm'

          - script: |
              set -e
              npm i -g azure-functions-core-tools@4 --unsafe-perm true
              func --version
            displayName: 'Install Azure Functions Core Tools'

          - script: |
              set -e
              # Azurite is required for Durable Functions locally (task hub + storage)
              npm i -g azurite
              azurite --version
            displayName: 'Install Azurite'

          - script: |
              set -e
              cd redaction-system

              mkdir -p .azurite
              rm -f azurite.log func-host.log func-host.pid azurite.pid

              echo "Starting Azurite..."
              nohup azurite --silent --location .azurite --debug azurite.log > /dev/null 2>&1 &
              echo $! > azurite.pid

              # Basic readiness check (Azurite listens on 10000/10001/10002)
              echo "Waiting for Azurite..."
              for i in $(seq 1 60); do
                nc -z 127.0.0.1 10000 >/dev/null 2>&1 && break || true
                sleep 1
              done
              if ! nc -z 127.0.0.1 10000 >/dev/null 2>&1; then
                echo "Azurite failed to start"
                tail -n 200 azurite.log || true
                exit 1
              fi
              echo "Azurite started OK"
            displayName: 'Start Azurite'

          - script: |
              set -e
              cd redaction-system/redactor

              echo "Starting Functions host..."
              nohup func start --port 7071 > ../func-host.log 2>&1 &
              echo $! > ../func-host.pid

              echo "Waiting for Functions host to be reachable..."
              for i in $(seq 1 60); do
                # /api/redact should exist once host is up
                if curl -fsS http://localhost:7071/api/redact >/dev/null 2>&1; then
                  echo "Functions host is up"
                  exit 0
                fi
                sleep 2
              done

              echo "Functions host did not become ready. Last 200 lines of host log:"
              tail -n 200 ../func-host.log || true
              exit 1
            displayName: 'Start local Azure Functions host (background) + wait'

          - script: |
              set -e
              cd redaction-system/redactor
              export PYTHONPATH=$(pwd)

              export E2E_FUNCTION_BASE_URL="http://localhost:7071"
              export E2E_STORAGE_ACCOUNT="pinsstredactiontestuks"
              export E2E_CONTAINER_NAME="pinsfuncredactionsystemtestuks-applease"
              export E2E_RUN_ID="ado-$(Build.BuildId)"
              export E2E_SKIP_REDACTION="false"

              # Avoid Managed Identity attempts on hosted agents (prevents noisy IMDS calls/time)
              export AZURE_IDENTITY_DISABLE_MANAGED_IDENTITY=true

              # Keep Azure SDK HTTP logs quiet (your e2e logger is the useful one)
              export AZURE_LOG_LEVEL=WARNING

              python3 -m pytest -m e2e -vv -rP --junitxml=junit/e2e_test_results.xml
            displayName: 'Run e2e tests'

          - script: |
              set +e
              cd redaction-system

              echo "Stopping Functions host..."
              if [ -f func-host.pid ]; then
                kill $(cat func-host.pid) >/dev/null 2>&1 || true
              fi
              pkill -f "func start" >/dev/null 2>&1 || true
              pkill -f "azure-functions-core-tools" >/dev/null 2>&1 || true
              pkill -f "workers/python" >/dev/null 2>&1 || true

              echo "Stopping Azurite..."
              if [ -f azurite.pid ]; then
                kill $(cat azurite.pid) >/dev/null 2>&1 || true
              fi
              pkill -f "azurite" >/dev/null 2>&1 || true

              echo "Done"
            displayName: 'Stop local hosts'
            condition: always()

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Functions host + Azurite logs'
            condition: always()
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/redaction-system'
              ArtifactName: 'e2e-local-host-logs'



            
          - script: |
              set -e
              cd redaction-system/redactor
              python3 -m coverage combine
              python3 -m coverage report
              python3 -m coverage xml -o coverage.xml
            displayName: 'Combine coverage reports'
          - task: UseDotNet@2
            displayName: 'Install latest .net'
            inputs:
              packageType: 'sdk'
              version: '8.x'
          - task: PublishCodeCoverageResults@2
            displayName: 'Publish coverage reports'
            inputs:
              summaryFileLocation: '$(Build.SourcesDirectory)/redaction-system/coverage.xml'
          - script: |
              set -e
              cd redaction-system/redactor
              python3 -m coverage report --fail-under=$(totalTestCoverageThreshold) --show-missing
            displayName: 'Fail if test coverage is below the threshold'
