name: Redaction CI/CD

# This is the main CI/CD pipeline of the the redaction system
parameters:
# User-specified environment to deploy to
- name: env
  default: 'dev'
  values:
  - 'dev'
  - 'test'
  - 'prod'

# Run when Pull Request raised to the main branch
pr:
- main

# Run when merged into main
trigger:
 branches:
  include:
    - main

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    validateName: Redaction CI
    globalVariables:
      - template: pipelines/azure-pipelines-variables.yml@self
    validationJobs:
      - name: ValidateCode
        steps:
          - checkout: self
            clean: true
          - script: |
              set -e
              cd redaction-system
              python3 -m pip install ruff
              export PYTHONPATH=$(pwd)
              python3 -m ruff check redactor
              python3 -m ruff format --check redactor
            displayName: 'Python code style check'
      - name: RunTestsJob
        steps:
          - checkout: self
            clean: true
          - checkout: templates
          - template: ../steps/azure_auth.yml@templates
            parameters:
              subscriptionId: $(SUBSCRIPTION_ID_${{ upper(parameters.env) }})
          - script: |
              set -e
              cd redaction-system
              python3 -m pip install -r redactor/requirements.txt
            displayName: 'Install requirements'
          - script: |
              set -e
              cd redaction-system/redactor
              export PYTHONPATH=$(pwd)
              python3 -m pytest test/unit_test -vv -rP -n 4 --junitxml=junit/unit_test_results.xml --cov="core" --cov-report=xml:unit_test_coverage.xml
              python3 -m coverage report --fail-under=$(unitTestCoverageThreshold) --show-missing
              mv .coverage .coverage.unit
            displayName: 'Run unit tests'
          - task: PublishTestResults@2
            displayName: 'Publish unit test results'
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/unit_test_results.xml'
              testRunTitle: 'Redaction System unit test report - $(Build.BuildId) - $(Build.SourceBranch)'
              mergeTestResults: true
          - script: |
              set -e
              cd redaction-system/redactor
              export PYTHONPATH=$(pwd)
              python3 -m pytest test/integration_test -vv -rP -n 4 --junitxml=junit/integration_test_results.xml --cov="core" --cov-report=xml:integration_test_coverage.xml
              python3 -m coverage report --fail-under=$(integrationTestCoverageThreshold) --show-missing
              mv .coverage .coverage.integration
            displayName: 'Run integration tests'
          - task: PublishTestResults@2
            displayName: 'Publish integration test results'
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/integration_test_results.xml'
              testRunTitle: 'Redaction System integration test report - $(Build.BuildId) - $(Build.SourceBranch)'
              mergeTestResults: true


          - script: |
              set -e
              sudo npm i -g azure-functions-core-tools@4 --unsafe-perm true
              func --version
            displayName: 'Install Azure Functions Core Tools'

          - script: |
              set -e
              cd redaction-system/redactor

              # Start Functions host in background
              nohup func start --port 7071 > ../func-host.log 2>&1 &
              echo $! > ../func-host.pid

              # Wait for host to come up
              for i in {1..60}; do
                curl -sSf http://localhost:7071/api/redact >/dev/null 2>&1 && break || true
                sleep 2
              done

              echo "Functions host started"
            displayName: 'Start local Azure Functions host'

          - script: |
              set -e
              cd redaction-system/redactor
              export PYTHONPATH=$(pwd)

              export E2E_FUNCTION_BASE_URL="http://localhost:7071"
              export E2E_STORAGE_ACCOUNT="pinsstredactiontestuks"
              export E2E_CONTAINER_NAME="pinsfuncredactionsystemtestuks-applease"
              export E2E_RUN_ID="ado-$(Build.BuildId)"
              export E2E_SKIP_REDACTION="false"
              export AZURE_IDENTITY_DISABLE_MANAGED_IDENTITY=true

              python3 -m pytest -m e2e -vv -rP --junitxml=junit/e2e_test_results.xml
            displayName: 'Run e2e tests'

          - script: |
              set +e
              echo "Stopping Functions host..."
              if [ -f redaction-system/func-host.pid ]; then
                kill $(cat redaction-system/func-host.pid) || true
              fi
              pkill -f "func start" || true
              pkill -f "azure-functions-core-tools" || true
              pkill -f "workers/python" || true
              echo "Done"
            displayName: 'Stop local Azure Functions host'
            condition: always()

          - task: PublishBuildArtifacts@1
            displayName: 'Publish func host log'
            condition: always()
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/redaction-system/func-host.log'
              ArtifactName: 'func-host-log'


            
          - script: |
              set -e
              cd redaction-system/redactor
              python3 -m coverage combine
              python3 -m coverage report
              python3 -m coverage xml -o coverage.xml
            displayName: 'Combine coverage reports'
          - task: UseDotNet@2
            displayName: 'Install latest .net'
            inputs:
              packageType: 'sdk'
              version: '8.x'
          - task: PublishCodeCoverageResults@2
            displayName: 'Publish coverage reports'
            inputs:
              summaryFileLocation: '$(Build.SourcesDirectory)/redaction-system/coverage.xml'
          - script: |
              set -e
              cd redaction-system/redactor
              python3 -m coverage report --fail-under=$(totalTestCoverageThreshold) --show-missing
            displayName: 'Fail if test coverage is below the threshold'
