name: Redaction CI/CD

# This is the main CI/CD pipeline of the the redaction system
parameters:
# User-specified environment to deploy to
- name: env
  default: 'dev'
  values:
  - 'dev'
  - 'test'
  - 'prod'

# Run when Pull Request raised to the main branch
pr:
- main

# Run when merged into main
trigger:
 branches:
  include:
    - main

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    validateName: Redaction CI
    globalVariables:
      - template: pipelines/azure-pipelines-variables.yml@self
    validationJobs:
      - name: ValidateCode
        steps:
          - checkout: self
            clean: true
          - script: |
              set -e
              cd redaction-system
              python3 -m pip install ruff
              export PYTHONPATH=$(pwd)
              python3 -m ruff check redactor
              python3 -m ruff format --check redactor
            displayName: 'Python code style check'
      - name: RunUnitTestsJob
        steps:
          - checkout: self
            clean: true
          - checkout: templates
          - template: ../steps/azure_auth.yml@templates
            parameters:
              subscriptionId: $(SUBSCRIPTION_ID_${{ upper(parameters.env) }})
          - script: |
              set -e
              cd redaction-system
              python3 -m pip install -r redactor/requirements.txt
              export PYTHONPATH=$(pwd)
              python3 -m pytest redactor/test/unit_test -vv -rP -n 4
            displayName: 'Run pytest for unit tests'
