name: Redaction CI/CD

# This is the main CI/CD pipeline of the the redaction system
parameters:
# User-specified environment to deploy to
- name: env
  default: 'dev'
  values:
  - 'dev'
  - 'test'
  - 'prod'

# Run when Pull Request raised to the main branch
pr:
- main

# Run when merged into main
trigger:
 branches:
  include:
    - main

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    validateName: Redaction CI
    globalVariables:
      - template: pipelines/azure-pipelines-variables.yml@self
    validationJobs:
      - name: ValidateCode
        steps:
          - checkout: self
            clean: true
          - script: |
              set -e
              cd redaction-system
              python3 -m pip install ruff
              export PYTHONPATH=$(pwd)
              python3 -m ruff check redactor
              python3 -m ruff format --check redactor
            displayName: 'Python code style check'
      - name: RunTestsJob
        steps:
          - checkout: self
            clean: true
          - checkout: templates
          - template: ../steps/azure_auth.yml@templates
            parameters:
              subscriptionId: $(SUBSCRIPTION_ID_${{ upper(parameters.env) }})
          - script: |
              set -e
              cd redaction-system
              python3 -m pip install -r redactor/requirements.txt
            displayName: 'Install requirements'
          - script: |
              set -e
              cd redaction-system
              export PYTHONPATH=$(pwd)
              python3 -m pytest redactor/test/unit_test -vv -rP -n 4 --junitxml=junit/unit_test_results.xml --cov="redactor/core" --cov-report=xml:unit_test_coverage.xml
              python3 -m coverage report --fail-under=$(unitTestCoverageThreshold) --show-missing
              echo "unit test file"
              ls
              mv .coverage .coverage.unit
              echo "after moving"
              ls
            displayName: 'Run unit tests'
          - task: PublishTestResults@2
            displayName: 'Publish unit test results'
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/unit_test_results.xml'
              testRunTitle: 'Redaction System unit test report - $(Build.BuildId) - $(Build.SourceBranch)'
              mergeTestResults: true
          - script: |
              set -e
              cd redaction-system
              export PYTHONPATH=$(pwd)
              python3 -m pytest redactor/test/integration_test -vv -rP -n 4 --junitxml=junit/integration_test_results.xml --cov="redactor/core" --cov-report=xml:integration_test_coverage.xml
              python3 -m coverage report --fail-under=$(integrationTestCoverageThreshold) --show-missing
              echo "int test file"
              ls
              mv .coverage .coverage.integration
              ech o "after moving"
              ls
            displayName: 'Run integration tests'
          - task: PublishTestResults@2
            displayName: 'Publish integration test results'
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/integration_test_results.xml'
              testRunTitle: 'Redaction System integration test report - $(Build.BuildId) - $(Build.SourceBranch)'
              mergeTestResults: true
          - script: |
              set -e
              cd redaction-system
              export PYTHONPATH=$(pwd)
              python3 -m pytest -m e2e -vv -rP --junitxml=junit/e2e_test_results.xml
            displayName: 'Run e2e tests'
          - task: PublishTestResults@2
            displayName: 'Publish e2e test results'
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/e2e_test_results.xml'
              testRunTitle: 'Redaction System e2e test report - $(Build.BuildId) - $(Build.SourceBranch)'
              mergeTestResults: true
          - script: |
              set -e
              cd redaction-system
              ls
              python3 -m coverage combine
              python3 -m coverage report
              python3 -m coverage xml -o coverage.xml
            displayName: 'Combine coverage reports'
          - task: UseDotNet@2
            displayName: 'Install latest .net'
            inputs:
              packageType: 'sdk'
              version: '8.x'
          - task: PublishCodeCoverageResults@2
            displayName: 'Publish coverage reports'
            inputs:
              summaryFileLocation: '$(Build.SourcesDirectory)/redaction-system/coverage.xml'
          - script: |
              set -e
              cd redaction-system
              python3 -m coverage report --fail-under=$(totalTestCoverageThreshold) --show-missing
            displayName: 'Fail if test coverage is below the threshold'
