pr: none

# run on merge, if there are changes
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - signature_detector/**

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 0
    globalVariables:
      - template: pipelines/azure-pipelines-variables.yml@self
    validationJobs:
      - name: Build signature detection
        steps:
          - task: AzureCLI@2
            displayName: 'Download model files'
            inputs:
              azureSubscription: 'Azure DevOps Pipelines - Redaction System - Deployment Dev'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -e
                python3 -m pip install huggingface_hub
                python3 pipelines/scripts/download_signature_detector_model.py --model-dir $(Build.SourcesDirectory)/signature_detector/model
          - template: ../steps/azure_web_app_docker_build_push.yml@templates
            parameters:
              azurecrName: $(azurecrName)
              workingDirectory: $(Build.SourcesDirectory)/signature_detector
              repository: redaction-system/signature-detector
